version: '3'

services:
  mongo:
    image: mongo:5.0.0
    restart: always
    volumes: 
      - 'my-app:/data/db'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    build: ./backend
    container_name: project-backend
    ports:
      - 8080:8080
    links:
      - mongo

  frontend:
    build: ./frontend
    container_name: project-frontend
    ports:
      - 3000:3000
    links:
      - backend


volumes:
  my-app: